# Generated by Django 4.1.4 on 2022-12-21 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='package',
            field=models.ForeignKey(help_text='Package', on_delete=django.db.models.deletion.PROTECT, related_name='deliverables', to='service.package', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='package',
            name='service_type',
            field=models.ForeignKey(help_text='Package service type', on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='service.servicetype', verbose_name='Service type'),
        ),
    ]
